#!/bin/bash

set -e

# What OVF to actually work on?
# This would normally be the Bio-Linux OVF, but for testing I have minibuntu
OVF="${OVF:-/home/tbooth_Public/packer/ubuntu_14.04_minimal.ova}"
FLAVOUR="${FLAVOUR:-vanilla}"
NETWORK="eoscloud-U-NERCvSE"
PUSH="${PUSH:-0}"

export PATH="$PATH:/opt/packer/packer_0.7:$HOME/packer/packer_0.7"
export CONFDIR="$(readlink -f "`dirname $0`")"
export PATCH_VMDK="$CONFDIR/patch_vmdk"

export PACKER_LOG=1
#export DEBUG=-debug

#Don't bother to have the script find itself; just run it in the current directory
munger="`readlink -f ../uploader/munger.py`"
uploader="`readlink -f ../uploader/uploader.py`"

# Note prerequisites to build this thingy:
## packer 0.7.x (download from packer.io)
## virtualbox (installed from .deb from virtualbox.org in my case)
## json_pp (comes with Perl, so you should have it)

# Build in my Public area because it's not on encrypted loopback
mkdir -p ~/Public/packer
cd ~/Public/packer

# Slightly paranoid/careful deletion of the old directory.
if [ -d output-virtualbox-ovf ] ; then
    rm output-virtualbox-ovf/*.ovf || true
    rm output-virtualbox-ovf/*.vmdk || true
    rmdir output-virtualbox-ovf
fi

# It's useful for me to be able to comment lines in the JSON, but Packer doesn't like
# this, so...
json_pp <"$CONFDIR"/packer.json >packer.pp.json ||
    cp "$CONFDIR"/packer.json packer.pp.json

packer build $DEBUG -only virtualbox-ovf -var confdir="$CONFDIR" -var ovf="$OVF" \
    -var flavour="$FLAVOUR" ./packer.pp.json

# This is a silly function.  But I like it.
make_prefix()
{
    log="$HOME/.pack_for_esx_upload.log"

    ( flock 9 || exit 1
      lastprfx=`tail -n1 "$log" | cut -d\| -f 1`
      echo $'\n'{a..z}{a..z} | grep -C1 $lastprfx | tail -n1 | tr -d '\n ' | tee -a "$log"
      echo "|`date`|$1" >> "$log"
    ) 9<"$log" || exit 1
}

# Patch the VMDK for VMWare.  This is idempotent and shouldn't stop it working in
# VirtualBox so do this every time.
for vmdk in output-virtualbox-ovf/*.vmdk ; do
    [ -f "$vmdk" ]
    "$PATCH_VMDK" "$vmdk"
done

# Munge the XML.  This sused to be done as part of the upload but I've split it out.
cd output-virtualbox-ovf/
ovf_to_push=`ls -t *.ovf | head -n 1`
[ -f "$ovf_to_push" ]

"$munger" "$FLAVOUR" "$NETWORK" < "$ovf_to_push" > munged.ovf

# Now push the result to EOS cloud
if [ "$PUSH" = 1 ] ; then

    prefix=`make_prefix "$OVF"`

    "$uploader" minibuntu --ovf_file munged.ovf --prefix $prefix

fi
